session 4455
PW-Sat2/mission pull request #930
Opened 2020-10-21 22:18 UTC by mlenczyk

2020-10-21 22:23 UTC, mandrek44 requested changes

2020-10-21 22:23 UTC, mandrek44 commented on sessions/4455/tasklist.py
> +    # Completed before this session: 75/181, no missing replies
Uzupełnij

2020-10-21 22:28 UTC, mlenczyk commented on sessions/4455/tasklist.py
> +    # Completed before this session: 75/181, no missing replies
done

2020-10-21 22:29 UTC, mlenczyk commented on sessions/4455/tasklist.py
> +    # Completed before this session: 75/181, no missing replies
w sumie źle, miało być 147 ;)

2020-10-22 06:13 UTC, alicjamusial approved these changes

2020-10-22 06:24 UTC, tom4r commented on sessions/4455/tasklist.py
> +    [tc.WriteProgramPart([3, 4, 5], 147 * 190, [0x45, 0xf6, 0xf0, 0x53, 0xe5, 0x50, 0x45, 0xf6, 0xf4, 0x53, 0x67, 0x22, 0xe7, 0x50, 0x45, 0xf6, 0xf8, 0x53, 0xe2, 0x54, 0x45, 0xf6, 0xfc, 0x53, 0x4, 0x
Ten był, czy nie?

2020-10-22 06:24 UTC, tom4r commented on sessions/4455/tasklist.py
> +    #[tc.FinalizeProgramEntry([3, 4, 5], 34304, 0x6333, "name"), Send, WaitMode.Wait],
To bym odkomentował.

2020-10-22 07:22 UTC, mlenczyk commented on sessions/4455/tasklist.py
> +    [tc.WriteProgramPart([3, 4, 5], 147 * 190, [0x45, 0xf6, 0xf0, 0x53, 0xe5, 0x50, 0x45, 0xf6, 0xf4, 0x53, 0x67, 0x22, 0xe7, 0x50, 0x45, 0xf6, 0xf8, 0x53, 0xe2, 0x54, 0x45, 0xf6, 0xfc, 0x53, 0x4, 0x
u nas nie było, no chyba że na hamsiakach?

2020-10-22 07:33 UTC, mlenczyk commented on sessions/4455/tasklist.py
> +    #[tc.FinalizeProgramEntry([3, 4, 5], 34304, 0x6333, "name"), Send, WaitMode.Wait],
done

2020-10-22 07:38 UTC, tom4r commented on sessions/4455/tasklist.py
> +    [tc.WriteProgramPart([3, 4, 5], 147 * 190, [0x45, 0xf6, 0xf0, 0x53, 0xe5, 0x50, 0x45, 0xf6, 0xf4, 0x53, 0x67, 0x22, 0xe7, 0x50, 0x45, 0xf6, 0xf8, 0x53, 0xe2, 0x54, 0x45, 0xf6, 0xfc, 0x53, 0x4, 0x
ok, dla pewności możemy wysłać.

2020-10-22 07:39 UTC, tom4r approved these changes

2020-10-22 07:40 UTC, mandrek44 approved these changes

2020-10-22 07:41 UTC, merged